# security team code scanning
WF_SLS_TEAM := "Security,cnisdp"
WF_SLS_DOMAIN := git.build.ingka.ikea.com
WF_SLS_ORG_NAME := china-digital-hub
WF_SLS_REPOS_NAME :=  "collage-web-design-new,3D-room,gpc-fullhouse-service,gpc-room-service,range-ocean,range-search,range-business,pax-online-web,pax-offline-web,pax-service,billy-online,billy-service,portal-service,sales-item-service,cms-service,ranking-service,recommendation-service,review-service,tagging-service,user-service,inspiration-service,mbff,comment-service,shopping-bff,ifood-service,locker-service,permission-center-service,event-booking-service,booking-service,cupid-service,sales-companion-service,store-companion-service,ipos-service,after-sales-service,checkoutservice,cnodi-swagger-files,delivery-service,finance-reconciliation,id-service,ikea-yht-h5,ikeacn-deploy-prod,ikeacn-deploy-test,inventory-api,inventory-search,inventory-web,i_deploy,jenkins-casc,master-data,moco,mpp-base,mpp-mock-service,mpp-platform,order-front-facade,order-history,order-hub,order-proxy,order-receiver,order-search,order-web,orders,orders-portal-web,order_reconciliation_script,order_tools,pubsub-service,repo-transfer-demo,sales-order-capture,service-hub,shoppingbag-service,shoppingbff-service,third-party-sync-service,web-order-module,yht,payments-be-ib-service,payments-fe-wecom-bff,payments-fe-portal-bff,payments-be-accounting,payments-be-eligibility,payments-be-facade,payments-be-gateway,payments-fc-service-mpp-payments,payments-fe-bff,payment-portal-fe,promotion-be-cr,promotion-be-discount-service,promotion-be-doraemon-admin,promotion-be-doraemon-service,promotion-be-pas,promotion-be-portal-identity-service,promotion-be-promotion-core,promotion-be-promotion-service,promotion-be-wepi,promotion-fe-channel-bff,promotion-fe-doraemon-bff,promotion-fe-portal-bff,promotion-fe-portal-gui,promotion-fe-promotion-bff,promotion-fe-wechat-redeem,promotion-fe-wecs,cch-be-push-service,cch-be-notification-gateway,cch-be-notification-service,cch-fe-notification-center-gui,promotion-be-customer-config-service,promotion-be-customer-filtering-service,promotion-be-customer-package-service,promotion-be-dms-service,promotion-be-distribution-service,promotion-fe-dms-portal-bff,geetest-proxy,ciam-mp-component,privacy-center,ciam,customer-segmentation,oneid,wechat-gw,customer-legacy-identity,oss-uploader,content-moderation,crypto-starter,fraud-detection,business-service,ciam-data-refresh-batch,loyalty,customer-admin-bff,kos,customer-aggregator,reference-data,customer-audit-log,prime-service,better-living,family-member-task-service,point-mall,family-bff,family-tier,family-tier-engine,family-coupon-aggregator,Business-Gateway,Business-Hub,Case-Management-Front,Case-Management,Configuration-portal-ui,Configuration-portal,imcc-webchat-driver,imcc-server,imcc-wechat-enterprise-driver,imcc-adapter-storage,imcc-adapter-genesys,imcc-common,Msg-Gateway,serverless-runner-testing,sls-clickhouse-sync-go,github-clickhouse-sync-go,inventory-portal-bff,mq-consumer,order-sync,app-jobs,GHAS_pipeline,tier,id-service,inventory-api"
WF_SLS_TYPE := "Org"
WF_SLS_SIZE := "1"
WF_SLS_SIZE_CPU := "4.0"
WF_SLS_SIZE_MEMORY := "8.0"
WF_SLS_CHARGE_LABELS := "cnisdp" #label should not contains blank
WF_SLS_RUNNER_GROUP := "default"
WF_SLS_LABELS := "code-scanning,china-digital-hub" #label should not contains blank
WF_SLS_ORG_URL := https://${WF_SLS_DOMAIN}/${WF_SLS_ORG_NAME}
WF_SLS_REG_ITEM := "{${WF_SLS_REG_COMMON}, \"Type\":\"${WF_SLS_TYPE}\",\"Name\":\"${WF_SLS_ORG_NAME}\",\"Url\":\"${WF_SLS_ORG_URL}\",\"Size\":\"${WF_SLS_SIZE}\",\"Cpu\":\"${WF_SLS_SIZE_CPU}\",\"Memory\":\"${WF_SLS_SIZE_MEMORY}\",\"Repos\":\"${WF_SLS_REPOS_NAME}\",\"Labels\":\"${WF_SLS_LABELS}\",\"ChargeLabels\":\"${WF_SLS_CHARGE_LABELS}\",\"RunnerGroup\":\"${WF_SLS_RUNNER_GROUP}\"}"
REG := $(WF_SLS_REG_ITEM)
WF_SLS_REGS := "[${REG}]"