# jira automation project
WF_SLS_DOMAIN := git.build.ingka.ikea.com
WF_SLS_ORG_NAME := ccoecn-panda
WF_SLS_REPOS_NAME := "pypanda.cloud,pypanda.alicloud,pypanda.core,cloud-observer,pypanda.capability,panda-service,panda-tasks"
WF_SLS_TYPE := "Org"  
WF_SLS_SIZE := "1"
WF_SLS_SIZE_CPU := "1.0"
WF_SLS_SIZE_MEMORY := "2.0"
WF_SLS_CHARGE_LABELS := "ccoecn-panda" #label should not contains blank
WF_SLS_LABELS := "ccoecn-panda,pypanda.alicloud,pypanda.core,cloud-observer,pypanda.capability,panda-service,panda-tasks" #label should not contains blank
WF_SLS_ORG_URL := https://${WF_SLS_DOMAIN}/${WF_SLS_ORG_NAME}
WF_SLS_REG_PANDA := "\"Pat\":\"${WF_SLS_PAT}\",\"Key\":\"${WF_SLS_KEY}\",\"Secret\":\"${WF_SLS_SECRET}\",\"Region\":\"${WF_SLS_REGION}\",\"SecGpId\":\"${WF_SLS_SECGROUP_ID}\",\"VSwitchId\":\"${WF_SLS_VSWITCH_ID}\",\"PullInterval\":\"300\""
WF_SLS_REG_ITEM3 := "{${WF_SLS_REG_PANDA}, \"Type\":\"${WF_SLS_TYPE}\",\"Name\":\"${WF_SLS_ORG_NAME}\",\"Url\":\"${WF_SLS_ORG_URL}\",\"Size\":\"${WF_SLS_SIZE}\",\"Cpu\":\"${WF_SLS_SIZE_CPU}\",\"Memory\":\"${WF_SLS_SIZE_MEMORY}\",\"Repos\":\"${WF_SLS_REPOS_NAME}\",\"Labels\":\"${WF_SLS_LABELS}\",\"ChargeLabels\":\"${WF_SLS_CHARGE_LABELS}\"}"
REG3 := $(WF_SLS_REG_ITEM3)
# cloud enablement CN project
WF_SLS_DOMAIN := git.build.ingka.ikea.com
WF_SLS_ORG_NAME := cloud-enablement-china
WF_SLS_REPOS_NAME := "serverless-native-run-dev,serverless-native-run-prod,serverless-runner-onboarding,serveless-runner-onboarding-plugin,network-onboarding"
WF_SLS_TYPE := "Org"
WF_SLS_SIZE := "1"
WF_SLS_SIZE_CPU := "1.0"
WF_SLS_SIZE_MEMORY := "2.0"
WF_SLS_LABELS := "serverless-native-run,serverless-runner-onboarding,serveless-runner-onboarding-plugin,network-onboarding" #label should not contains blank
WF_SLS_CHARGE_LABELS := "cloud-enablement-china" #label should not contains blank
WF_SLS_ORG_URL := https://${WF_SLS_DOMAIN}/${WF_SLS_ORG_NAME}
WF_SLS_REG_CEC := "\"Pat\":\"${WF_SLS_PAT}\",\"Key\":\"${WF_SLS_KEY}\",\"Secret\":\"${WF_SLS_SECRET}\",\"Region\":\"${WF_SLS_REGION}\",\"SecGpId\":\"${WF_SLS_SECGROUP_ID}\",\"VSwitchId\":\"${WF_SLS_VSWITCH_ID}\",\"PullInterval\":\"300\""
WF_SLS_REG_ITEM4 := "{${WF_SLS_REG_CEC}, \"Type\":\"${WF_SLS_TYPE}\",\"Name\":\"${WF_SLS_ORG_NAME}\",\"Url\":\"${WF_SLS_ORG_URL}\",\"Size\":\"${WF_SLS_SIZE}\",\"Cpu\":\"${WF_SLS_SIZE_CPU}\",\"Memory\":\"${WF_SLS_SIZE_MEMORY}\",\"Repos\":\"${WF_SLS_REPOS_NAME}\",\"Labels\":\"${WF_SLS_LABELS}\",\"ChargeLabels\":\"${WF_SLS_CHARGE_LABELS}\"}"
REG4 := $(WF_SLS_REG_ITEM4)
# br & runner project
WF_SLS_DOMAIN := github.com
WF_SLS_ORG_NAME := ingka-group-digital
WF_SLS_REPOS_NAME := "cdh-br-ark-ei,cdh-br-ark-impl-alirdspg-ccoecn,serverless-hosted-runner,grafana-image-renderer-sdk-go"
WF_SLS_TYPE := "Org"  
WF_SLS_SIZE := "1"
WF_SLS_SIZE_CPU := "1.0"
WF_SLS_SIZE_MEMORY := "2.0"
WF_SLS_CHARGE_LABELS := "cdh-br-serverless-hosted-runner" #label should not contains blank
WF_SLS_LABELS := "cdh-br-ark-ei,cdh-br-ark-impl-alirdspg-ccoecn,serverless-hosted-runner,grafana-image-renderer-sdk-go" #label should not contains blank
WF_SLS_ORG_URL := https://${WF_SLS_DOMAIN}/${WF_SLS_ORG_NAME}
WF_SLS_PULL_INTERVAL_Sec := 60
WF_SLS_REG_COMMON_GITHUB := "\"Pat\":\"${WF_SLS_PAT}\",\"Key\":\"${WF_SLS_KEY}\",\"Secret\":\"${WF_SLS_SECRET}\",\"Region\":\"${WF_SLS_REGION}\",\"SecGpId\":\"${WF_SLS_SECGROUP_ID}\",\"VSwitchId\":\"${WF_SLS_VSWITCH_ID}\",\"PullInterval\":\"300\""
WF_SLS_REG_ITEM5 := "{${WF_SLS_REG_COMMON_GITHUB}, \"Type\":\"${WF_SLS_TYPE}\",\"Name\":\"${WF_SLS_ORG_NAME}\",\"Url\":\"${WF_SLS_ORG_URL}\",\"Size\":\"${WF_SLS_SIZE}\",\"Cpu\":\"${WF_SLS_SIZE_CPU}\",\"Memory\":\"${WF_SLS_SIZE_MEMORY}\",\"Repos\":\"${WF_SLS_REPOS_NAME}\",\"Labels\":\"${WF_SLS_LABELS}\",\"ChargeLabels\":\"${WF_SLS_CHARGE_LABELS}\",\"ImageVersion\":\"${WF_SLS_BR_IMAGE_VER}\"}"
REG5 := $(WF_SLS_REG_ITEM5)
# fin project
WF_SLS_DOMAIN := git.build.ingka.ikea.com
WF_SLS_ORG_NAME := ccoe-cn-fintool
WF_SLS_REPOS_NAME := "fintool-jobs,icft-account,ikea-cn-cloud-fin-tool-deploy,icft-jobs,azurecn-jobs,optscale,fintool-invoice-tool,icft-frontend,fin-test"
WF_SLS_TYPE := "Org"  
WF_SLS_SIZE := "1"
WF_SLS_SIZE_CPU := "1.0"
WF_SLS_SIZE_MEMORY := "2.0"
WF_SLS_CHARGE_LABELS := "ccoe-cn-fintool" #label should not contains blank
WF_SLS_LABELS := "self-hosted,fintool-runner,fintool-jobs" #label should not contains blank
WF_SLS_ORG_URL := https://${WF_SLS_DOMAIN}/${WF_SLS_ORG_NAME}
WF_SLS_REG_FIN := "\"Pat\":\"${WF_SLS_PAT}\",\"Key\":\"${WF_SLS_KEY}\",\"Secret\":\"${WF_SLS_SECRET}\",\"Region\":\"${WF_SLS_REGION}\",\"SecGpId\":\"${WF_SLS_SECGROUP_ID}\",\"VSwitchId\":\"${WF_SLS_VSWITCH_ID}\",\"PullInterval\":\"300\""
WF_SLS_REG_ITEM6 := "{${WF_SLS_REG_FIN}, \"Type\":\"${WF_SLS_TYPE}\",\"Name\":\"${WF_SLS_ORG_NAME}\",\"Url\":\"${WF_SLS_ORG_URL}\",\"Size\":\"${WF_SLS_SIZE}\",\"Cpu\":\"${WF_SLS_SIZE_CPU}\",\"Memory\":\"${WF_SLS_SIZE_MEMORY}\",\"Repos\":\"${WF_SLS_REPOS_NAME}\",\"Labels\":\"${WF_SLS_LABELS}\",\"ChargeLabels\":\"${WF_SLS_CHARGE_LABELS}\"}"
REG6 := $(WF_SLS_REG_ITEM6)
# One Solution CN https://jira.digital.ingka.com/servicedesk/customer/portal/3/CMSSD-28531
WF_SLS_DOMAIN := git.build.ingka.ikea.com
WF_SLS_ORG_NAME := CN-One-Solution
WF_SLS_REPOS_NAME := "icontact-bff,vue3-pnpm-monorepo,Case-Management-Front-Plus"
WF_SLS_TYPE := "Org"  
WF_SLS_SIZE := "1"
WF_SLS_SIZE_CPU := "2.0"
WF_SLS_SIZE_MEMORY := "4.0"
WF_SLS_CHARGE_LABELS := "cncs-icontact" #label should not contains blank
WF_SLS_LABELS := "cncs-runner" #label should not contains blank
WF_SLS_ORG_URL := https://${WF_SLS_DOMAIN}/${WF_SLS_ORG_NAME}
WF_SLS_PULL_INTERVAL_Sec := 15
WF_SLS_REG_ONE_SOLUTION := "\"Pat\":\"\",\"Key\":\"${CNONESOLUTION_ALICLOUD_ACCESS_KEY}\",\"Secret\":\"${CNONESOLUTION_ALICLOUD_SECRET_KEY}\",\"Region\":\"${WF_SLS_REGION}\",\"SecGpId\":\"${RUNNER_SG_ID_CNONESOLUTION}\",\"VSwitchId\":\"${RUNNER_VSWITCH_ID_CNONESOLUTION}\",\"PullInterval\":\"${WF_SLS_PULL_INTERVAL_Sec}\""
WF_SLS_REG_ITEM7 := "{${WF_SLS_REG_ONE_SOLUTION}, \"Type\":\"${WF_SLS_TYPE}\",\"Name\":\"${WF_SLS_ORG_NAME}\",\"Url\":\"${WF_SLS_ORG_URL}\",\"Size\":\"${WF_SLS_SIZE}\",\"Cpu\":\"${WF_SLS_SIZE_CPU}\",\"Memory\":\"${WF_SLS_SIZE_MEMORY}\",\"Repos\":\"${WF_SLS_REPOS_NAME}\",\"Labels\":\"${WF_SLS_LABELS}\",\"ChargeLabels\":\"${WF_SLS_CHARGE_LABELS}\"}"
REG7 := $(WF_SLS_REG_ITEM7)
# sentry-exporter
WF_SLS_DOMAIN := git.build.ingka.ikea.com
WF_SLS_ORG_NAME := labrador
WF_SLS_REPOS_NAME := "sentry-exporter"
WF_SLS_TYPE := "Org"  
WF_SLS_SIZE := "1"
WF_SLS_SIZE_CPU := "1.0"
WF_SLS_SIZE_MEMORY := "2.0"
WF_SLS_CHARGE_LABELS := "sentry-exporter" #label should not contains blank
WF_SLS_LABELS := "sentry-exporter-cicd" #label should not contains blank
WF_SLS_ORG_URL := https://${WF_SLS_DOMAIN}/${WF_SLS_ORG_NAME}
WF_SLS_PULL_INTERVAL_Sec := 60
WF_SLS_REG_SENTRY_EXP := "\"Pat\":\"${WF_SLS_PAT}\",\"Key\":\"${WF_SLS_KEY}\",\"Secret\":\"${WF_SLS_SECRET}\",\"Region\":\"${WF_SLS_REGION}\",\"SecGpId\":\"${WF_SLS_SECGROUP_ID}\",\"VSwitchId\":\"${WF_SLS_VSWITCH_ID}\",\"PullInterval\":\"300\""
WF_SLS_REG_ITEM8 := "{${WF_SLS_REG_SENTRY_EXP}, \"Type\":\"${WF_SLS_TYPE}\",\"Name\":\"${WF_SLS_ORG_NAME}\",\"Url\":\"${WF_SLS_ORG_URL}\",\"Size\":\"${WF_SLS_SIZE}\",\"Cpu\":\"${WF_SLS_SIZE_CPU}\",\"Memory\":\"${WF_SLS_SIZE_MEMORY}\",\"Repos\":\"${WF_SLS_REPOS_NAME}\",\"Labels\":\"${WF_SLS_LABELS}\",\"ChargeLabels\":\"${WF_SLS_CHARGE_LABELS}\"}"
REG8 := $(WF_SLS_REG_ITEM8)
WF_SLS_REGS := "[${REG3},${REG4},${REG5},${REG6},${REG7},${REG8}]"
