apiVersion: apps/v1
kind: Deployment
metadata:   
  name: kube-despatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      serverless.runner.service: kube-despatcher
  template:
    metadata:  
      labels:
        serverless.runner.service: kube-despatcher
    spec:
      imagePullSecrets:
        - name: sls-image-pull-secret
      containers:
        - image: artifactory.cloud.ingka-system.cn/ccoecn-docker-virtual/serverless-hosted-dispatcher:${image_v}
          name: kube-despatcher
          resources: {}
      restartPolicy: Always
status: {}
